/// Standard library import providing allocation and memory utilities.
const std = @import("std");
/// OpenGL bindings import providing buffer targets, usage flags and GL buffer functions.
const gl = @import("gl");

/// Creates a generic OpenGL buffer wrapper parameterized by element type.
/// Provides an opaque handle around a GL buffer object with cached state and
/// a deferred `Editor` for batched updates.
/// Parameters:
///   - data_: Element type stored in the buffer; determines count calculations.
///
/// Returns:
///   - Opaque buffer type handling GL buffer objects for the given element type.
pub fn Buffer(comptime data_: type) type {
    const Impl = struct {
        /// OpenGL buffer object name (ID) generated by `glGenBuffers`. Zero means not yet created or deleted.
        id: u32 = 0,
        /// Buffer binding target that determines how the buffer is interpreted by GL.
        target: gl.buffers.BufferTarget = .array_buffer,
        /// Usage hint for GL about expected access pattern, e.g., static draw or dynamic draw.
        usage: gl.buffers.BufferUsage = .static_draw,
        /// Size of the buffer store in bytes as last set via `bufferData` or `reserve`.
        size_bytes: usize = 0,
        /// Number of elements of type `data_` currently stored; derived from `size_bytes`.
        count: usize = 0,
        /// Whether the buffer is currently mapped to client address space.
        mapped: bool = false,
        /// Access flags used for the current mapping, if any; null when unmapped.
        access: ?gl.buffers.MapAccess = null,
    };

    return opaque {
        /// Alias for this opaque buffer type, used for method signatures.
        const Self = @This();
        /// Returns a mutable pointer to the underlying `Impl` storage.
        /// Parameters:
        ///   - self: Opaque buffer handle to reinterpret as `Impl`.
        ///
        /// Returns:
        ///   - Mutable pointer to the `Impl` instance.
        inline fn impl(self: *Self) *Impl {
            return @ptrCast(@alignCast(self));
        }
        /// Returns a const pointer to the underlying `Impl` storage.
        /// Parameters:
        ///   - self: Const opaque buffer handle to reinterpret as `Impl`.
        ///
        /// Returns:
        ///   - Const pointer to the `Impl` instance.
        inline fn implConst(self: *const Self) *const Impl {
            return @ptrCast(@alignCast(self));
        }

        /// Element type stored in this buffer instantiation.
        pub const DataType = data_;

        /// Creates a new buffer object.
        /// Allocates `Impl`, initializes it with defaults and generates a GL buffer name.
        /// Parameters:
        ///   - allocator: Allocator used to allocate the `Impl` structure.
        ///
        /// Returns:
        ///   - Pointer to the newly created buffer on success.
        ///   - Allocation or other error on failure.
        pub fn create(allocator: std.mem.Allocator) !*@This() {
            const m = try allocator.create(Impl);
            m.* = .{};
            var id: u32 = 0;
            if (gl.loader.loaded()) {
                gl.buffers.gen(1, @ptrCast(&id));
            } else {
                id = 1;
            }
            m.id = id;
            return @ptrCast(m);
        }
        /// Destroys the buffer object and frees its storage.
        /// Deletes the GL buffer name if non-zero and destroys the `Impl` allocation.
        /// Parameters:
        ///   - self: Buffer to destroy.
        ///   - allocator: Allocator that was used to create the buffer.
        ///
        /// Returns:
        ///   - void.
        pub fn destroy(self: *@This(), allocator: std.mem.Allocator) void {
            const m = self.impl();
            if (gl.loader.loaded() and m.id != 0) gl.buffers.delete(1, @ptrCast(&m.id));
            allocator.destroy(m);
        }

        /// Checks whether the buffer name corresponds to a valid GL buffer.
        /// Parameters:
        ///   - self: Buffer to validate.
        ///
        /// Returns:
        ///   - True if the ID is non-zero and `glIsBuffer` succeeds, false otherwise.
        pub fn isValid(self: *const @This()) bool {
            const m = self.implConst();
            return m.id != 0 and gl.buffers.isBuffer(m.id);
        }

        /// Returns the GL buffer object name (ID).
        /// Parameters:
        ///   - self: Buffer to query.
        ///
        /// Returns:
        ///   - GL buffer name as `u32`.
        pub fn getId(self: *const @This()) u32 {
            return self.implConst().id;
        }
        /// Returns the buffer binding target.
        /// Parameters:
        ///   - self: Buffer to query.
        ///
        /// Returns:
        ///   - Buffer target enumeration.
        pub fn getTarget(self: *const @This()) gl.buffers.BufferTarget {
            return self.implConst().target;
        }
        /// Returns the usage hint for the buffer.
        /// Parameters:
        ///   - self: Buffer to query.
        ///
        /// Returns:
        ///   - Buffer usage enumeration.
        pub fn getUsage(self: *const @This()) gl.buffers.BufferUsage {
            return self.implConst().usage;
        }
        /// Returns the size of the buffer store in bytes.
        /// Parameters:
        ///   - self: Buffer to query.
        ///
        /// Returns:
        ///   - Size in bytes as `usize`.
        pub fn getSizeBytes(self: *const @This()) usize {
            return self.implConst().size_bytes;
        }
        /// Returns the number of elements of type `DataType` stored.
        /// Parameters:
        ///   - self: Buffer to query.
        ///
        /// Returns:
        ///   - Element count as `usize`.
        pub fn getCount(self: *const @This()) usize {
            return self.implConst().count;
        }
        /// Returns the element type of this buffer instantiation.
        /// Parameters:
        ///   - _: Buffer instance (unused, only for method syntax).
        ///
        /// Returns:
        ///   - The comptime type `data_`.
        pub fn getDataType(_: *const @This()) type {
            return data_;
        }
        /// Returns whether the buffer is currently mapped.
        /// Parameters:
        ///   - self: Buffer to query.
        ///
        /// Returns:
        ///   - True if mapped, false otherwise.
        pub fn getIsMapped(self: *const @This()) bool {
            return self.implConst().mapped;
        }

        /// Queries the GL buffer size parameter after binding the buffer.
        /// Parameters:
        ///   - self: Buffer whose size to query from GL.
        ///
        /// Returns:
        ///   - Buffer size in bytes as reported by GL via `GL_BUFFER_SIZE`.
        pub fn querySize(self: *const @This()) i32 {
            const m = self.implConst();
            gl.buffers.bind(m.target, m.id);
            var v: i32 = 0;
            gl.buffers.getParameter(m.target, .buffer_size, @ptrCast(&v));
            return v;
        }
        /// Queries the GL buffer usage parameter after binding the buffer.
        /// Parameters:
        ///   - self: Buffer whose usage to query from GL.
        ///
        /// Returns:
        ///   - Buffer usage as reported by GL via `GL_BUFFER_USAGE` as `i32`.
        pub fn queryUsage(self: *const @This()) i32 {
            const m = self.implConst();
            gl.buffers.bind(m.target, m.id);
            var v: i32 = 0;
            gl.buffers.getParameter(m.target, .buffer_usage, @ptrCast(&v));
            return v;
        }
        /// Queries whether the GL buffer is currently mapped after binding.
        /// Parameters:
        ///   - self: Buffer to query.
        ///
        /// Returns:
        ///   - True if GL reports the buffer as mapped, false otherwise.
        pub fn queryMapped(self: *const @This()) bool {
            const m = self.implConst();
            gl.buffers.bind(m.target, m.id);
            var v: i32 = 0;
            gl.buffers.getParameter(m.target, .buffer_mapped, @ptrCast(&v));
            return v != 0;
        }
        /// Queries the GL buffer map length after binding the buffer.
        /// Parameters:
        ///   - self: Buffer to query.
        ///
        /// Returns:
        ///   - Map length as reported by GL via `GL_BUFFER_MAP_LENGTH` as `i32`.
        pub fn queryMapLength(self: *const @This()) i32 {
            const m = self.implConst();
            gl.buffers.bind(m.target, m.id);
            var v: i32 = 0;
            gl.buffers.getParameter(m.target, .buffer_map_length, @ptrCast(&v));
            return v;
        }
        /// Queries the GL buffer map offset after binding the buffer.
        /// Parameters:
        ///   - self: Buffer to query.
        ///
        /// Returns:
        ///   - Map offset as reported by GL via `GL_BUFFER_MAP_OFFSET` as `i32`.
        pub fn queryMapOffset(self: *const @This()) i32 {
            const m = self.implConst();
            gl.buffers.bind(m.target, m.id);
            var v: i32 = 0;
            gl.buffers.getParameter(m.target, .buffer_map_offset, @ptrCast(&v));
            return v;
        }
        /// Queries the GL buffer access flags after binding the buffer.
        /// Parameters:
        ///   - self: Buffer to query.
        ///
        /// Returns:
        ///   - Access flags as reported by GL via `GL_BUFFER_ACCESS_FLAGS` as `i32`.
        pub fn queryAccessFlags(self: *const @This()) i32 {
            const m = self.implConst();
            gl.buffers.bind(m.target, m.id);
            var v: i32 = 0;
            gl.buffers.getParameter(m.target, .buffer_access_flags, @ptrCast(&v));
            return v;
        }

        /// Binds the buffer to its current target.
        /// Parameters:
        ///   - self: Buffer to bind.
        ///
        /// Returns:
        ///   - void.
        pub fn bind(self: *const @This()) void {
            const m = self.implConst();
            gl.buffers.bind(m.target, m.id);
        }
        /// Binds the buffer to a specific target.
        /// Parameters:
        ///   - self: Buffer to bind.
        ///   - target: Buffer target to bind to.
        ///
        /// Returns:
        ///   - void.
        pub fn bindTo(self: *const @This(), target: gl.buffers.BufferTarget) void {
            gl.buffers.bind(target, self.implConst().id);
        }
        /// Alias for `bind`. Binds the buffer to its current target.
        /// Parameters:
        ///   - self: Buffer to bind.
        ///
        /// Returns:
        ///   - void.
        pub fn use(self: *const @This()) void {
            self.bind();
        }

        /// Creates an `Editor` for deferred buffer configuration.
        /// Parameters:
        ///   - self: Buffer to edit.
        ///
        /// Returns:
        ///   - Initialized `Editor` instance referencing this buffer.
        pub fn edit(self: *Self) Editor {
            return Editor.init(self);
        }

        /// Builder that batches pending buffer state changes and applies them at once.
        /// Stores optional pending values for target, usage, data uploads, sub-data,
        /// reserve, copy, bind base/range, mapping, flushing and unmapping.
        /// Call `apply` to flush all queued operations to GL and cached state.
        pub const Editor = struct {
            /// Reference to the buffer being edited.
            _buffer: *Self,
            /// Pending buffer target override to be applied on `apply`.
            _pending_target: ?gl.buffers.BufferTarget = null,
            /// Pending usage hint override to be applied on `apply`.
            _pending_usage: ?gl.buffers.BufferUsage = null,
            /// Pending typed data upload for `glBufferData`.
            _pending_data: ?struct {
                /// Slice of typed elements to upload.
                slice: []const data_,
                /// Usage hint for the new store.
                usage: gl.buffers.BufferUsage,
            } = null,
            /// Pending raw byte upload for `glBufferData`.
            _pending_data_bytes: ?struct {
                /// Raw bytes to upload.
                bytes: []const u8,
                /// Usage hint for the new store.
                usage: gl.buffers.BufferUsage,
            } = null,
            /// Pending byte range update for `glBufferSubData`.
            _pending_sub_data: ?struct {
                /// Byte offset within the buffer store.
                offset: usize,
                /// Bytes to write at the given offset.
                bytes: []const u8,
            } = null,
            /// Pending typed range update for `glBufferSubData`.
            _pending_sub_data_typed: ?struct {
                /// Element offset within the buffer store.
                offset_elements: usize,
                /// Slice of typed elements to write.
                slice: []const data_,
            } = null,
            /// Pending store reservation without initial data for `glBufferData`.
            _pending_reserve: ?struct {
                /// Size in bytes to allocate.
                size_bytes: usize,
                /// Usage hint for the new store.
                usage: gl.buffers.BufferUsage,
            } = null,
            /// Pending copy operation between buffer targets via `glCopyBufferSubData`.
            _pending_copy: ?struct {
                /// Source buffer target for the copy read.
                read_target: gl.buffers.BufferTarget,
                /// Byte offset in the source buffer.
                read_offset: usize,
                /// Byte offset in the destination buffer (this buffer).
                write_offset: usize,
                /// Number of bytes to copy.
                size: usize,
            } = null,
            /// Pending indexed binding via `glBindBufferBase`.
            _pending_bind_base: ?struct {
                /// Target for indexed binding, e.g., uniform or shader storage.
                target: gl.buffers.BufferTarget,
                /// Index of the binding point.
                index: u32,
            } = null,
            /// Pending ranged indexed binding via `glBindBufferRange`.
            _pending_bind_range: ?struct {
                /// Target for indexed binding.
                target: gl.buffers.BufferTarget,
                /// Index of the binding point.
                index: u32,
                /// Byte offset within the buffer.
                offset: usize,
                /// Number of bytes to bind.
                size: usize,
            } = null,
            /// Pending map operation via `glMapBufferRange`.
            _pending_map: ?struct {
                /// Byte offset to begin mapping.
                offset: usize,
                /// Length in bytes to map.
                length: usize,
                /// Access flags for the mapping.
                access: gl.buffers.MapAccess,
            } = null,
            /// Whether to unmap the buffer on `apply`.
            _pending_unmap: bool = false,
            /// Pending flush of a mapped range via `glFlushMappedBufferRange`.
            _pending_flush: ?struct {
                /// Byte offset of the range to flush.
                offset: usize,
                /// Length in bytes of the range to flush.
                length: usize,
            } = null,

            /// Initializes an editor for the given buffer.
            /// Parameters:
            ///   - buffer: Buffer to be edited; stored by reference.
            ///
            /// Returns:
            ///   - Initialized `Editor` with no pending changes.
            pub fn init(buffer: *Self) Editor {
                return .{ ._buffer = buffer };
            }

            /// Queues a buffer target change.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - target: New buffer target to apply.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setTarget(self: *const Editor, target: gl.buffers.BufferTarget) *const Editor {
                @constCast(self)._pending_target = target;
                return @constCast(self);
            }
            /// Queues a usage hint change.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - usage: New usage hint to apply.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setUsage(self: *const Editor, usage: gl.buffers.BufferUsage) *const Editor {
                @constCast(self)._pending_usage = usage;
                return @constCast(self);
            }
            /// Queues a typed data upload via `glBufferData`.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - data: Slice of typed elements to upload.
            ///   - usage: Usage hint for the new store.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setData(self: *const Editor, data: []const data_, usage: gl.buffers.BufferUsage) *const Editor {
                @constCast(self)._pending_data = .{ .slice = data, .usage = usage };
                return @constCast(self);
            }
            /// Queues a raw byte upload via `glBufferData`.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - bytes: Raw bytes to upload.
            ///   - usage: Usage hint for the new store.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setDataBytes(self: *const Editor, bytes: []const u8, usage: gl.buffers.BufferUsage) *const Editor {
                @constCast(self)._pending_data_bytes = .{ .bytes = bytes, .usage = usage };
                return @constCast(self);
            }
            /// Queues a store reservation without initial data.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - size_bytes: Size in bytes to allocate.
            ///   - usage: Usage hint for the new store.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn reserve(self: *const Editor, size_bytes: usize, usage: gl.buffers.BufferUsage) *const Editor {
                @constCast(self)._pending_reserve = .{ .size_bytes = size_bytes, .usage = usage };
                return @constCast(self);
            }
            /// Queues a byte sub-data update via `glBufferSubData`.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - offset: Byte offset within the buffer.
            ///   - bytes: Bytes to write.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setSubData(self: *const Editor, offset: usize, bytes: []const u8) *const Editor {
                @constCast(self)._pending_sub_data = .{ .offset = offset, .bytes = bytes };
                return @constCast(self);
            }
            /// Queues a typed sub-data update via `glBufferSubData`.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - offset_elements: Element offset within the buffer.
            ///   - slice: Slice of typed elements to write.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setSubDataTyped(self: *const Editor, offset_elements: usize, slice: []const data_) *const Editor {
                @constCast(self)._pending_sub_data_typed = .{ .offset_elements = offset_elements, .slice = slice };
                return @constCast(self);
            }
            /// Queues a copy operation via `glCopyBufferSubData`.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - read_target: Source buffer target for the copy.
            ///   - read_offset: Byte offset in the source buffer.
            ///   - write_offset: Byte offset in the destination buffer.
            ///   - size: Number of bytes to copy.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setCopySubData(self: *const Editor, read_target: gl.buffers.BufferTarget, read_offset: usize, write_offset: usize, size: usize) *const Editor {
                @constCast(self)._pending_copy = .{ .read_target = read_target, .read_offset = read_offset, .write_offset = write_offset, .size = size };
                return @constCast(self);
            }
            /// Queues an indexed binding via `glBindBufferBase`.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - target: Target for indexed binding.
            ///   - index: Index of the binding point.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setBindBase(self: *const Editor, target: gl.buffers.BufferTarget, index: u32) *const Editor {
                @constCast(self)._pending_bind_base = .{ .target = target, .index = index };
                return @constCast(self);
            }
            /// Queues a ranged indexed binding via `glBindBufferRange`.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - target: Target for indexed binding.
            ///   - index: Index of the binding point.
            ///   - offset: Byte offset within the buffer.
            ///   - size: Number of bytes to bind.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setBindRange(self: *const Editor, target: gl.buffers.BufferTarget, index: u32, offset: usize, size: usize) *const Editor {
                @constCast(self)._pending_bind_range = .{ .target = target, .index = index, .offset = offset, .size = size };
                return @constCast(self);
            }
            /// Queues a map operation via `glMapBufferRange`.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - offset: Byte offset to begin mapping.
            ///   - length: Length in bytes to map.
            ///   - access: Access flags for the mapping.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setMap(self: *const Editor, offset: usize, length: usize, access: gl.buffers.MapAccess) *const Editor {
                @constCast(self)._pending_map = .{ .offset = offset, .length = length, .access = access };
                return @constCast(self);
            }
            /// Queues an unmap operation via `glUnmapBuffer`.
            /// Parameters:
            ///   - self: Editor instance.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setUnmap(self: *const Editor) *const Editor {
                @constCast(self)._pending_unmap = true;
                return @constCast(self);
            }
            /// Queues a flush of a mapped range via `glFlushMappedBufferRange`.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - offset: Byte offset of the range to flush.
            ///   - length: Length in bytes of the range to flush.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setFlushMappedRange(self: *const Editor, offset: usize, length: usize) *const Editor {
                @constCast(self)._pending_flush = .{ .offset = offset, .length = length };
                return @constCast(self);
            }
            /// Queues a typed data upload using the current or pending usage hint.
            /// Convenience wrapper around `setData` that reuses cached usage if none is pending.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - data: Slice of typed elements to upload.
            ///
            /// Returns:
            ///   - Pointer to the editor for chaining.
            pub fn setDataSimple(self: *const Editor, data: []const data_) *const Editor {
                const u = @constCast(self)._pending_usage orelse @constCast(self)._buffer.implConst().usage;
                return self.setData(data, u);
            }

            /// Applies all pending changes to GL and cached state.
            /// Binds the buffer as needed, executes `bufferData`, `bufferSubData`,
            /// `copySubData`, `bindBase`, `bindRange`, `map`, `flushMappedRange`
            /// and `unmap` operations in order, then resets pending state.
            /// Parameters:
            ///   - self: Editor instance holding pending operations.
            ///
            /// Returns:
            ///   - void.
            pub fn apply(self: *const Editor) void {
                const loaded = gl.loader.loaded();
                const buf = @constCast(self)._buffer.impl();
                const target = @constCast(self)._pending_target orelse buf.target;
                if (@constCast(self)._pending_target) |t| buf.target = t;
                if (@constCast(self)._pending_usage) |u| buf.usage = u;
                if (@constCast(self)._pending_data) |d| {
                    if (loaded) gl.buffers.bind(target, buf.id);
                    const bytes: []const u8 = std.mem.sliceAsBytes(d.slice);
                    if (loaded) gl.buffers.bufferData(target, bytes.len, bytes.ptr, d.usage);
                    buf.size_bytes = bytes.len;
                    buf.count = d.slice.len;
                    buf.usage = d.usage;
                } else if (@constCast(self)._pending_data_bytes) |d| {
                    if (loaded) gl.buffers.bind(target, buf.id);
                    if (loaded) gl.buffers.bufferData(target, d.bytes.len, d.bytes.ptr, d.usage);
                    buf.size_bytes = d.bytes.len;
                    buf.count = d.bytes.len / @sizeOf(data_);
                    buf.usage = d.usage;
                } else if (@constCast(self)._pending_reserve) |r| {
                    if (loaded) gl.buffers.bind(target, buf.id);
                    if (loaded) gl.buffers.bufferData(target, r.size_bytes, null, r.usage);
                    buf.size_bytes = r.size_bytes;
                    buf.count = r.size_bytes / @sizeOf(data_);
                    buf.usage = r.usage;
                }
                if (@constCast(self)._pending_sub_data) |s| {
                    if (loaded) gl.buffers.bind(target, buf.id);
                    if (loaded) gl.buffers.bufferSubData(target, s.offset, s.bytes.len, s.bytes.ptr);
                }
                if (@constCast(self)._pending_sub_data_typed) |s| {
                    if (loaded) gl.buffers.bind(target, buf.id);
                    const bytes = std.mem.sliceAsBytes(s.slice);
                    const off = s.offset_elements * @sizeOf(data_);
                    if (loaded) gl.buffers.bufferSubData(target, off, bytes.len, bytes.ptr);
                }
                if (@constCast(self)._pending_copy) |c| if (loaded) gl.buffers.copySubData(c.read_target, target, c.read_offset, c.write_offset, c.size);
                if (@constCast(self)._pending_bind_base) |b| if (loaded) gl.buffers.bindBase(b.target, b.index, buf.id);
                if (@constCast(self)._pending_bind_range) |r| if (loaded) gl.buffers.bindRange(r.target, r.index, buf.id, @intCast(r.offset), @intCast(r.size));
                if (@constCast(self)._pending_map) |m| {
                    if (loaded) gl.buffers.bind(target, buf.id);
                    if (loaded) _ = gl.buffers.map(target, m.offset, m.length, m.access);
                    buf.mapped = true;
                    buf.access = m.access;
                }
                if (@constCast(self)._pending_flush) |f| if (loaded) gl.buffers.flushMappedRange(target, f.offset, f.length);
                if (@constCast(self)._pending_unmap) {
                    var ok: bool = false;
                    if (loaded) ok = gl.buffers.unmap(target);
                    buf.mapped = !ok;
                    if (ok) buf.access = null;
                }
                @constCast(self).* = Editor.init(@constCast(self)._buffer);
            }

            /// Immediately maps a range of the buffer and updates cached state.
            /// Binds the buffer to the effective target and calls `glMapBufferRange`.
            /// Parameters:
            ///   - self: Editor instance.
            ///   - offset: Byte offset to begin mapping.
            ///   - length: Length in bytes to map.
            ///   - access: Access flags for the mapping.
            ///
            /// Returns:
            ///   - Mapped pointer as `?*anyopaque` on success, null if mapping failed or GL not loaded.
            pub fn mapNow(self: *const Editor, offset: usize, length: usize, access: gl.buffers.MapAccess) ?*anyopaque {
                const buf = @constCast(self)._buffer.impl();
                const target = @constCast(self)._pending_target orelse buf.target;
                if (gl.loader.loaded()) gl.buffers.bind(target, buf.id);
                const ptr = if (gl.loader.loaded()) gl.buffers.map(target, offset, length, access) else null;
                if (ptr != null) {
                    buf.mapped = true;
                    buf.access = access;
                }
                return ptr;
            }
            /// Immediately unmaps the buffer and updates cached state.
            /// Binds the effective target and calls `glUnmapBuffer`.
            /// Parameters:
            ///   - self: Editor instance.
            ///
            /// Returns:
            ///   - True if unmapping succeeded, false otherwise.
            pub fn unmapNow(self: *const Editor) bool {
                const buf = @constCast(self)._buffer.impl();
                const target = @constCast(self)._pending_target orelse buf.target;
                var ok: bool = false;
                if (gl.loader.loaded()) ok = gl.buffers.unmap(target) != 0;
                buf.mapped = !ok;
                if (ok) buf.access = null;
                return ok;
            }
        };
    };
}
