const std = @import("std");
const gl = @import("gl");

// Generic linked program from vertex and optional fragment shader wrappers.
// `vert_` and `frag_` are expected to be types generated by VertexDescriptor
// / FragmentDescriptor (with .instance(), .Uniform, .IdCache, .Editor, .edit).
pub fn ShaderProgram(comptime vert_: type, comptime frag_: ?type) type {
    const has_frag = frag_ != null;
    const FragType = if (has_frag) frag_.? else void;
    return struct {
        const Self = @This();
        pub const Vert = vert_;
        pub const Frag = frag_;
        pub const HasFrag = has_frag;

        // ---- opaque program state ----
        _id: u32 = 0,
        _initialized: bool = false,

        // Uniform location caches — populated on instance() creation.
        pub var vert_cache: Vert.IdCache = if (@hasDecl(Vert, "IdCache")) std.mem.zeroes(Vert.IdCache) else undefined;
        pub var frag_cache: if (has_frag) FragType.IdCache else void = if (has_frag) std.mem.zeroes(FragType.IdCache) else {};

        // Global singleton per specialization (comptime type creates unique static)
        var _singleton: ?Self = null;

        pub var id: u32 = 0;

        pub fn instance() Self {
            if (_singleton) |s| {
                if (s._initialized and s._id != 0) return s;
            }
            const prog_id = gl.programs.create();
            const vs = Vert.instance();
            gl.programs.attach(prog_id, vs);
            if (comptime has_frag) {
                const fs = FragType.instance();
                gl.programs.attach(prog_id, fs);
            }
            gl.programs.link(prog_id);
            var ok: i32 = 0;
            gl.programs.getParameter(prog_id, .link_status, &ok);
            if (ok == 0) {
                var log: [512]u8 = undefined;
                _ = gl.programs.getInfoLog(prog_id, &log);
            }
            // Populate uniform caches
            inline for (@typeInfo(Vert.Uniform).@"struct".fields) |field| {
                const loc = gl.uniforms.location(prog_id, @ptrCast(field.name));
                @field(vert_cache, field.name) = loc;
            }
            if (comptime has_frag) {
                inline for (@typeInfo(FragType.Uniform).@"struct".fields) |field| {
                    const loc = gl.uniforms.location(prog_id, @ptrCast(field.name));
                    @field(frag_cache, field.name) = loc;
                }
            }
            const self = Self{ ._id = prog_id, ._initialized = true };
            id = prog_id;
            _singleton = self;
            return self;
        }

        pub fn dispose(self: *Self) void {
            if (self._id != 0) {
                gl.programs.delete(self._id);
                self._id = 0;
                self._initialized = false;
                id = 0;
                _singleton = null;
            }
        }

        pub fn getId(self: *const Self) u32 { return self._id; }
        pub fn getVertCache(_: *const Self) Vert.IdCache { return vert_cache; }
        pub fn getFragCache(_: *const Self) if (has_frag) FragType.IdCache else void {
            if (comptime has_frag) return frag_cache else return {};
        }

        pub fn use(self: *const Self) void {
            gl.programs.use(self._id);
        }

        // Editors for vert / frag uniform blocks — delegates to shader wrappers
        pub fn vertEdit(self: *const Self) Vert.Editor {
            return Vert.edit(self._id);
        }
        pub fn fragEdit(self: *const Self) if (has_frag) FragType.Editor else void {
            if (comptime has_frag) return FragType.edit(self._id) else return {};
        }

        // Static helpers that use singleton
        pub fn vertEditStatic() Vert.Editor {
            const s = instance();
            return s.vertEdit();
        }
        pub fn fragEditStatic() if (has_frag) FragType.Editor else void {
            if (comptime has_frag) {
                const s = instance();
                return s.fragEdit();
            } else return {};
        }

        pub fn useStatic() void {
            const s = instance();
            s.use();
        }
    };
}
