/// Standard library import providing allocation and utility functions.
const std = @import("std");
/// OpenGL bindings import providing texture targets, formats, filters and GL functions.
const gl = @import("gl");

/// Internal storage for a GL texture object and its cached state.
/// Mirrors the GL texture name and all mutable texture parameters to allow
/// deferred editing via `Texture.Editor` and to avoid redundant GL queries.
const Impl = struct {
    /// OpenGL texture object name (ID) generated by `glGenTextures`. Zero means not yet created or deleted.
    id: u32 = 0,
    /// Texture binding target that determines how the texture is interpreted by GL.
    target: gl.textures.TextureTarget = .texture_2d,
    /// Sized internal format of the texture image, if defined (e.g., RGBA8). Null means unspecified.
    internal_format: ?gl.textures.InternalFormat = null,
    /// Width in texels of the base level image.
    width: i32 = 0,
    /// Height in texels of the base level image. Zero for 1D textures.
    height: i32 = 0,
    /// Depth in texels for 3D or array textures. Zero for 2D textures.
    depth: i32 = 0,
    /// Number of mipmap levels allocated for immutable storage.
    levels: i32 = 1,
    /// External pixel format used for `glTexImage` uploads, if known.
    pixel_format: ?gl.textures.PixelFormat = null,
    /// Data type of pixel data used for uploads, if known.
    data_type: ?gl.enums.DataType = null,
    /// Minification filter controlling sampling when the texture is minified.
    min_filter: gl.textures.TextureMinFilter = .nearest_mipmap_linear,
    /// Magnification filter controlling sampling when the texture is magnified.
    mag_filter: gl.textures.TextureMagFilter = .linear,
    /// Wrapping mode for the S (U) texture coordinate.
    wrap_s: gl.textures.TextureWrap = .repeat,
    /// Wrapping mode for the T (V) texture coordinate.
    wrap_t: gl.textures.TextureWrap = .repeat,
    /// Wrapping mode for the R (W) texture coordinate, used for 3D textures.
    wrap_r: gl.textures.TextureWrap = .repeat,
    /// Depth texture comparison mode (none or compareRefToTexture).
    compare_mode: gl.textures.CompareMode = .none,
    /// Depth comparison function used when `compare_mode` is enabled.
    compare_func: gl.textures.CompareFunc = .lequal,
    /// Base mipmap level for texture sampling.
    base_level: i32 = 0,
    /// Maximum mipmap level that can be sampled.
    max_level: i32 = 1000,
    /// Minimum level-of-detail parameter.
    min_lod: f32 = -1000.0,
    /// Maximum level-of-detail parameter.
    max_lod: f32 = 1000.0,
    /// Component swizzle for the red channel.
    swizzle_r: gl.textures.Swizzle = .red,
    /// Component swizzle for the green channel.
    swizzle_g: gl.textures.Swizzle = .green,
    /// Component swizzle for the blue channel.
    swizzle_b: gl.textures.Swizzle = .blue,
    /// Component swizzle for the alpha channel.
    swizzle_a: gl.textures.Swizzle = .alpha,
    /// Whether mipmaps have been generated for this texture.
    has_mipmap: bool = false,
    /// Cached active texture unit last used to bind this texture.
    active_unit: gl.textures.TextureUnit = .texture0,
};

/// Opaque GL texture wrapper providing type-safe access to `Impl` storage.
/// The texture is allocated with an allocator and holds a GL name, dimensions,
/// format, filtering, wrapping, swizzle and LOD state. Use `edit` to obtain
/// an `Editor` for deferred, batched state changes.
pub const Texture = opaque {
    /// Returns a mutable pointer to the underlying `Impl` storage.
    /// Parameters:
    ///   - self: Opaque texture handle to reinterpret as `Impl`.
    /// Returns:
    ///   - Mutable pointer to the `Impl` instance.
    inline fn impl(self: *Texture) *Impl {
        return @ptrCast(@alignCast(self));
    }
    /// Returns a const pointer to the underlying `Impl` storage.
    /// Parameters:
    ///   - self: Const opaque texture handle to reinterpret as `Impl`.
    /// Returns:
    ///   - Const pointer to the `Impl` instance.
    inline fn implConst(self: *const Texture) *const Impl {
        return @ptrCast(@alignCast(self));
    }

    /// Creates a new texture object.
    /// Allocates `Impl`, initializes it with defaults and generates a GL texture name.
    /// Parameters:
    ///   - allocator: Allocator used to allocate the `Impl` structure.
    /// Returns:
    ///   - Pointer to the newly created `Texture` on success.
    ///   - Allocation or other error on failure.
    pub fn create(allocator: std.mem.Allocator) !*Texture {
        const m = try allocator.create(Impl);
        m.* = .{};
        var id: u32 = 0;
        if (gl.loader.loaded()) {
            gl.textures.gen(1, @ptrCast(&id));
        } else {
            id = 1;
        }
        m.id = id;
        return @ptrCast(m);
    }

    /// Alias for `create`. Creates a new texture object.
    /// Parameters:
    ///   - allocator: Allocator used to allocate the `Impl` structure.
    /// Returns:
    ///   - Pointer to the newly created `Texture`.
    pub fn init(allocator: std.mem.Allocator) !*Texture {
        return create(allocator);
    }

    /// Destroys the texture object and frees its storage.
    /// Deletes the GL texture name if non-zero and destroys the `Impl` allocation.
    /// Parameters:
    ///   - self: Texture to destroy.
    ///   - allocator: Allocator that was used to create the texture.
    /// Returns:
    ///   - void.
    pub fn destroy(self: *Texture, allocator: std.mem.Allocator) void {
        const m = self.impl();
        if (gl.loader.loaded() and m.id != 0) gl.textures.delete(1, @ptrCast(&m.id));
        allocator.destroy(m);
    }

    /// Alias for `destroy`. Deinitializes the texture.
    /// Parameters:
    ///   - self: Texture to deinitialize.
    ///   - allocator: Allocator that was used to create the texture.
    /// Returns:
    ///   - void.
    pub fn deinit(self: *Texture, allocator: std.mem.Allocator) void {
        self.destroy(allocator);
    }

    /// Checks whether the texture name corresponds to a valid GL texture.
    /// Parameters:
    ///   - self: Texture to validate.
    /// Returns:
    ///   - True if the ID is non-zero and `glIsTexture` succeeds, false otherwise.
    pub fn isValid(self: *const Texture) bool {
        const m = self.implConst();
        return m.id != 0 and gl.textures.isTexture(m.id);
    }

    /// Returns the GL texture object name (ID).
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - GL texture name as `u32`.
    pub fn getId(self: *const Texture) u32 {
        return self.implConst().id;
    }
    /// Returns the texture binding target.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Texture target enumeration.
    pub fn getTarget(self: *const Texture) gl.textures.TextureTarget {
        return self.implConst().target;
    }
    /// Returns the sized internal format, if set.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Optional internal format; null if not yet specified.
    pub fn getInternalFormat(self: *const Texture) ?gl.textures.InternalFormat {
        return self.implConst().internal_format;
    }
    /// Returns the base level width in texels.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Width as `i32`.
    pub fn getWidth(self: *const Texture) i32 {
        return self.implConst().width;
    }
    /// Returns the base level height in texels.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Height as `i32`.
    pub fn getHeight(self: *const Texture) i32 {
        return self.implConst().height;
    }
    /// Returns the base level depth in texels.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Depth as `i32`.
    pub fn getDepth(self: *const Texture) i32 {
        return self.implConst().depth;
    }
    /// Returns the number of mipmap levels.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Level count as `i32`.
    pub fn getLevels(self: *const Texture) i32 {
        return self.implConst().levels;
    }
    /// Returns the external pixel format, if known.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Optional pixel format.
    pub fn getPixelFormat(self: *const Texture) ?gl.textures.PixelFormat {
        return self.implConst().pixel_format;
    }
    /// Returns the pixel data type, if known.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Optional data type.
    pub fn getDataType(self: *const Texture) ?gl.enums.DataType {
        return self.implConst().data_type;
    }
    /// Returns the minification filter.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Minification filter enumeration.
    pub fn getMinFilter(self: *const Texture) gl.textures.TextureMinFilter {
        return self.implConst().min_filter;
    }
    /// Returns the magnification filter.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Magnification filter enumeration.
    pub fn getMagFilter(self: *const Texture) gl.textures.TextureMagFilter {
        return self.implConst().mag_filter;
    }
    /// Returns the wrap mode for the S coordinate.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Wrap mode for S.
    pub fn getWrapS(self: *const Texture) gl.textures.TextureWrap {
        return self.implConst().wrap_s;
    }
    /// Returns the wrap mode for the T coordinate.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Wrap mode for T.
    pub fn getWrapT(self: *const Texture) gl.textures.TextureWrap {
        return self.implConst().wrap_t;
    }
    /// Returns the wrap mode for the R coordinate.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Wrap mode for R.
    pub fn getWrapR(self: *const Texture) gl.textures.TextureWrap {
        return self.implConst().wrap_r;
    }
    /// Returns the depth texture comparison mode.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Comparison mode enumeration.
    pub fn getCompareMode(self: *const Texture) gl.textures.CompareMode {
        return self.implConst().compare_mode;
    }
    /// Returns the depth comparison function.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Comparison function enumeration.
    pub fn getCompareFunc(self: *const Texture) gl.textures.CompareFunc {
        return self.implConst().compare_func;
    }
    /// Returns the base mipmap level.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Base level as `i32`.
    pub fn getBaseLevel(self: *const Texture) i32 {
        return self.implConst().base_level;
    }
    /// Returns the maximum mipmap level.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Maximum level as `i32`.
    pub fn getMaxLevel(self: *const Texture) i32 {
        return self.implConst().max_level;
    }
    /// Returns the minimum level-of-detail value.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Minimum LOD as `f32`.
    pub fn getMinLod(self: *const Texture) f32 {
        return self.implConst().min_lod;
    }
    /// Returns the maximum level-of-detail value.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Maximum LOD as `f32`.
    pub fn getMaxLod(self: *const Texture) f32 {
        return self.implConst().max_lod;
    }
    /// Returns the swizzle component for the red channel.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Swizzle enumeration for red.
    pub fn getSwizzleR(self: *const Texture) gl.textures.Swizzle {
        return self.implConst().swizzle_r;
    }
    /// Returns the swizzle component for the green channel.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Swizzle enumeration for green.
    pub fn getSwizzleG(self: *const Texture) gl.textures.Swizzle {
        return self.implConst().swizzle_g;
    }
    /// Returns the swizzle component for the blue channel.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Swizzle enumeration for blue.
    pub fn getSwizzleB(self: *const Texture) gl.textures.Swizzle {
        return self.implConst().swizzle_b;
    }
    /// Returns the swizzle component for the alpha channel.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Swizzle enumeration for alpha.
    pub fn getSwizzleA(self: *const Texture) gl.textures.Swizzle {
        return self.implConst().swizzle_a;
    }
    /// Returns whether mipmaps have been generated.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - True if mipmaps were generated, false otherwise.
    pub fn getHasMipmap(self: *const Texture) bool {
        return self.implConst().has_mipmap;
    }
    /// Returns the cached active texture unit.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Active texture unit enumeration.
    pub fn getActiveUnit(self: *const Texture) gl.textures.TextureUnit {
        return self.implConst().active_unit;
    }

    /// Returns the texture dimensions as a struct.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Anonymous struct with fields `w`, `h`, `d` representing width, height and depth.
    pub fn getSize(self: *const Texture) struct { w: i32, h: i32, d: i32 } {
        const m = self.implConst();
        return .{ .w = m.width, .h = m.height, .d = m.depth };
    }
    /// Returns the four component swizzle values.
    /// Parameters:
    ///   - self: Texture to query.
    /// Returns:
    ///   - Array of four `Swizzle` values in RGBA order.
    pub fn getSwizzle(self: *const Texture) [4]gl.textures.Swizzle {
        const m = self.implConst();
        return .{ m.swizzle_r, m.swizzle_g, m.swizzle_b, m.swizzle_a };
    }

    /// Binds the texture to its current target using the current active unit.
    /// Parameters:
    ///   - self: Texture to bind.
    /// Returns:
    ///   - void.
    pub fn bind(self: *const Texture) void {
        const m = self.implConst();
        gl.textures.bind(m.target, m.id);
    }
    /// Binds the texture to a specific texture unit.
    /// Activates the given unit and then binds the texture.
    /// Parameters:
    ///   - self: Texture to bind.
    ///   - unit: Texture unit to activate before binding.
    /// Returns:
    ///   - void.
    pub fn bindToUnit(self: *const Texture, unit: gl.textures.TextureUnit) void {
        gl.textures.activeTexture(unit);
        self.bind();
    }
    /// Alias for `bind`. Binds the texture to its target.
    /// Parameters:
    ///   - self: Texture to bind.
    /// Returns:
    ///   - void.
    pub fn use(self: *const Texture) void {
        self.bind();
    }
    /// Alias for `bindToUnit`. Binds the texture to a specific unit.
    /// Parameters:
    ///   - self: Texture to bind.
    ///   - unit: Texture unit to activate.
    /// Returns:
    ///   - void.
    pub fn useUnit(self: *const Texture, unit: gl.textures.TextureUnit) void {
        self.bindToUnit(unit);
    }

    /// Queries an integer texture parameter from GL after binding the texture.
    /// Parameters:
    ///   - self: Texture whose parameter to query.
    ///   - pname: Name of the texture parameter to query.
    /// Returns:
    ///   - Integer value of the parameter.
    pub fn queryParameterI(self: *const Texture, pname: gl.textures.TextureParameter) i32 {
        self.bind();
        var v: i32 = 0;
        gl.textures.getParameterI(self.implConst().target, pname, @ptrCast(&v));
        return v;
    }
    /// Queries a float texture parameter from GL after binding the texture.
    /// Parameters:
    ///   - self: Texture whose parameter to query.
    ///   - pname: Name of the texture parameter to query.
    /// Returns:
    ///   - Floating point value of the parameter.
    pub fn queryParameterF(self: *const Texture, pname: gl.textures.TextureParameter) f32 {
        self.bind();
        var v: f32 = 0;
        gl.textures.getParameterF(self.implConst().target, pname, @ptrCast(&v));
        return v;
    }

    /// Creates an `Editor` for deferred texture configuration.
    /// Parameters:
    ///   - self: Texture to edit.
    /// Returns:
    ///   - Initialized `Editor` instance referencing this texture.
    pub fn edit(self: *Texture) Editor {
        return Editor.init(self);
    }

    /// Builder that batches pending texture state changes and applies them at once.
    /// Stores optional pending values for storage, image specification, filtering,
    /// wrapping, LOD, swizzle and generic parameters. Call `apply` to flush.
    pub const Editor = struct {
        /// Reference to the texture being edited.
        _texture: *Texture,

        /// Pending texture target override to be applied on `apply`.
        _pending_target: ?gl.textures.TextureTarget = null,
        /// Pending immutable 2D storage specification (levels, format, size).
        _pending_storage2d: ?struct {
            /// Texture target for the storage allocation.
            target: gl.textures.TextureTarget,
            /// Number of mipmap levels to allocate.
            levels: i32,
            /// Sized internal format for the storage.
            internalformat: gl.textures.InternalFormat,
            /// Width in texels.
            width: i32,
            /// Height in texels.
            height: i32,
        } = null,
        /// Pending immutable 3D storage specification (levels, format, size).
        _pending_storage3d: ?struct {
            /// Texture target for the storage allocation.
            target: gl.textures.TextureTarget,
            /// Number of mipmap levels to allocate.
            levels: i32,
            /// Sized internal format for the storage.
            internalformat: gl.textures.InternalFormat,
            /// Width in texels.
            width: i32,
            /// Height in texels.
            height: i32,
            /// Depth in texels.
            depth: i32,
        } = null,
        /// Pending 2D image specification for `glTexImage2D`.
        _pending_image2d: ?struct {
            /// Texture target for the image.
            target: gl.textures.TextureTarget,
            /// Mipmap level.
            level: i32,
            /// Sized internal format.
            internalformat: gl.textures.InternalFormat,
            /// Width in texels.
            width: i32,
            /// Height in texels.
            height: i32,
            /// Border width, must be 0 in core profile.
            border: i32,
            /// External pixel format of the supplied data.
            format: gl.textures.PixelFormat,
            /// Data type of the supplied pixel data.
            kind: gl.enums.DataType,
            /// Pointer to pixel data or null to allocate without initialization.
            pixels: ?*const anyopaque,
        } = null,
        /// Pending 3D image specification for `glTexImage3D`.
        _pending_image3d: ?struct {
            /// Texture target for the image.
            target: gl.textures.TextureTarget,
            /// Mipmap level.
            level: i32,
            /// Sized internal format.
            internalformat: gl.textures.InternalFormat,
            /// Width in texels.
            width: i32,
            /// Height in texels.
            height: i32,
            /// Depth in texels.
            depth: i32,
            /// Border width.
            border: i32,
            /// External pixel format.
            format: gl.textures.PixelFormat,
            /// Data type of pixel data.
            kind: gl.enums.DataType,
            /// Pointer to pixel data or null.
            pixels: ?*const anyopaque,
        } = null,
        /// Pending 2D sub-image update for `glTexSubImage2D`.
        _pending_sub2d: ?struct {
            /// Texture target for the sub-image.
            target: gl.textures.TextureTarget,
            /// Mipmap level to update.
            level: i32,
            /// X offset within the texture.
            xoffset: i32,
            /// Y offset within the texture.
            yoffset: i32,
            /// Width of the sub-region.
            width: i32,
            /// Height of the sub-region.
            height: i32,
            /// External pixel format.
            format: gl.textures.PixelFormat,
            /// Data type of pixel data.
            kind: gl.enums.DataType,
            /// Pointer to pixel data or null.
            pixels: ?*const anyopaque,
        } = null,
        /// Pending 3D sub-image update for `glTexSubImage3D`.
        _pending_sub3d: ?struct {
            /// Texture target for the sub-image.
            target: gl.textures.TextureTarget,
            /// Mipmap level to update.
            level: i32,
            /// X offset within the texture.
            xoffset: i32,
            /// Y offset within the texture.
            yoffset: i32,
            /// Z offset within the texture.
            zoffset: i32,
            /// Width of the sub-region.
            width: i32,
            /// Height of the sub-region.
            height: i32,
            /// Depth of the sub-region.
            depth: i32,
            /// External pixel format.
            format: gl.textures.PixelFormat,
            /// Data type of pixel data.
            kind: gl.enums.DataType,
            /// Pointer to pixel data or null.
            pixels: ?*const anyopaque,
        } = null,
        /// Pending compressed 2D image specification.
        _pending_compressed2d: ?struct {
            /// Texture target for the compressed image.
            target: gl.textures.TextureTarget,
            /// Mipmap level.
            level: i32,
            /// Compressed internal format.
            internalformat: gl.textures.InternalFormat,
            /// Width in texels.
            width: i32,
            /// Height in texels.
            height: i32,
            /// Border width.
            border: i32,
            /// Size of compressed data in bytes.
            image_size: i32,
            /// Pointer to compressed data or null.
            data: ?*const anyopaque,
        } = null,
        /// Pending compressed 3D image specification.
        _pending_compressed3d: ?struct {
            /// Texture target for the compressed image.
            target: gl.textures.TextureTarget,
            /// Mipmap level.
            level: i32,
            /// Compressed internal format.
            internalformat: gl.textures.InternalFormat,
            /// Width in texels.
            width: i32,
            /// Height in texels.
            height: i32,
            /// Depth in texels.
            depth: i32,
            /// Border width.
            border: i32,
            /// Size of compressed data in bytes.
            image_size: i32,
            /// Pointer to compressed data or null.
            data: ?*const anyopaque,
        } = null,
        /// Pending copy from framebuffer to 2D texture.
        _pending_copy2d: ?struct {
            /// Texture target for the copy.
            target: gl.textures.TextureTarget,
            /// Mipmap level.
            level: i32,
            /// Sized internal format for the new image.
            internalformat: gl.textures.InternalFormat,
            /// Window X coordinate of the lower-left corner to copy from.
            x: i32,
            /// Window Y coordinate of the lower-left corner to copy from.
            y: i32,
            /// Width of the region to copy.
            width: i32,
            /// Height of the region to copy.
            height: i32,
            /// Border width.
            border: i32,
        } = null,
        /// Pending copy from framebuffer to 2D sub-image.
        _pending_copy_sub2d: ?struct {
            /// Texture target for the copy.
            target: gl.textures.TextureTarget,
            /// Mipmap level.
            level: i32,
            /// X offset within the texture.
            xoffset: i32,
            /// Y offset within the texture.
            yoffset: i32,
            /// Window X coordinate to copy from.
            x: i32,
            /// Window Y coordinate to copy from.
            y: i32,
            /// Width of the region.
            width: i32,
            /// Height of the region.
            height: i32,
        } = null,
        /// Pending copy from framebuffer to 3D sub-image.
        _pending_copy_sub3d: ?struct {
            /// Texture target for the copy.
            target: gl.textures.TextureTarget,
            /// Mipmap level.
            level: i32,
            /// X offset within the texture.
            xoffset: i32,
            /// Y offset within the texture.
            yoffset: i32,
            /// Z offset within the texture.
            zoffset: i32,
            /// Window X coordinate to copy from.
            x: i32,
            /// Window Y coordinate to copy from.
            y: i32,
            /// Width of the region.
            width: i32,
            /// Height of the region.
            height: i32,
        } = null,

        /// Pending minification filter override.
        _pending_min_filter: ?gl.textures.TextureMinFilter = null,
        /// Pending magnification filter override.
        _pending_mag_filter: ?gl.textures.TextureMagFilter = null,
        /// Pending wrap mode for S coordinate.
        _pending_wrap_s: ?gl.textures.TextureWrap = null,
        /// Pending wrap mode for T coordinate.
        _pending_wrap_t: ?gl.textures.TextureWrap = null,
        /// Pending wrap mode for R coordinate.
        _pending_wrap_r: ?gl.textures.TextureWrap = null,
        /// Pending depth comparison mode.
        _pending_compare_mode: ?gl.textures.CompareMode = null,
        /// Pending depth comparison function.
        _pending_compare_func: ?gl.textures.CompareFunc = null,
        /// Pending base mipmap level.
        _pending_base_level: ?i32 = null,
        /// Pending maximum mipmap level.
        _pending_max_level: ?i32 = null,
        /// Pending minimum LOD value.
        _pending_min_lod: ?f32 = null,
        /// Pending maximum LOD value.
        _pending_max_lod: ?f32 = null,
        /// Pending swizzle for red channel.
        _pending_swizzle_r: ?gl.textures.Swizzle = null,
        /// Pending swizzle for green channel.
        _pending_swizzle_g: ?gl.textures.Swizzle = null,
        /// Pending swizzle for blue channel.
        _pending_swizzle_b: ?gl.textures.Swizzle = null,
        /// Pending swizzle for alpha channel.
        _pending_swizzle_a: ?gl.textures.Swizzle = null,
        /// Whether to generate mipmaps on `apply`.
        _pending_generate_mipmap: bool = false,
        /// Pending active texture unit override.
        _pending_active_unit: ?gl.textures.TextureUnit = null,
        /// Pending generic integer texture parameter.
        _pending_param_i: ?struct {
            /// Name of the texture parameter.
            pname: gl.textures.TextureParameter,
            /// Integer value to set.
            param: i32,
        } = null,
        /// Pending generic float texture parameter.
        _pending_param_f: ?struct {
            /// Name of the texture parameter.
            pname: gl.textures.TextureParameter,
            /// Floating point value to set.
            param: f32,
        } = null,

        /// Initializes an editor for the given texture.
        /// Parameters:
        ///   - texture: Texture to be edited; stored by reference.
        /// Returns:
        ///   - Initialized `Editor` with no pending changes.
        pub fn init(texture: *Texture) Editor {
            return .{ ._texture = texture };
        }

        /// Queues a texture target change.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: New texture target to apply.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setTarget(self: *const Editor, target: gl.textures.TextureTarget) *const Editor {
            @constCast(self)._pending_target = target;
            return @constCast(self);
        }
        /// Queues an active texture unit change.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - unit: Texture unit to activate on `apply`.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setActiveUnit(self: *const Editor, unit: gl.textures.TextureUnit) *const Editor {
            @constCast(self)._pending_active_unit = unit;
            return @constCast(self);
        }
        /// Queues immutable storage allocation for a 2D texture.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: Texture target.
        ///   - levels: Number of mipmap levels.
        ///   - internalformat: Sized internal format.
        ///   - width: Width in texels.
        ///   - height: Height in texels.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setStorage2D(self: *const Editor, target: gl.textures.TextureTarget, levels: i32, internalformat: gl.textures.InternalFormat, width: i32, height: i32) *const Editor {
            @constCast(self)._pending_storage2d = .{ .target = target, .levels = levels, .internalformat = internalformat, .width = width, .height = height };
            return @constCast(self);
        }
        /// Queues immutable storage allocation for a 2D texture using the current or pending target.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - levels: Number of mipmap levels.
        ///   - internalformat: Sized internal format.
        ///   - width: Width in texels.
        ///   - height: Height in texels.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setStorage2DSimple(self: *const Editor, levels: i32, internalformat: gl.textures.InternalFormat, width: i32, height: i32) *const Editor {
            const tgt = @constCast(self)._pending_target orelse @constCast(self)._texture.implConst().target;
            return self.setStorage2D(tgt, levels, internalformat, width, height);
        }
        /// Queues immutable storage allocation for a 3D texture.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: Texture target.
        ///   - levels: Number of mipmap levels.
        ///   - internalformat: Sized internal format.
        ///   - width: Width in texels.
        ///   - height: Height in texels.
        ///   - depth: Depth in texels.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setStorage3D(self: *const Editor, target: gl.textures.TextureTarget, levels: i32, internalformat: gl.textures.InternalFormat, width: i32, height: i32, depth: i32) *const Editor {
            @constCast(self)._pending_storage3d = .{ .target = target, .levels = levels, .internalformat = internalformat, .width = width, .height = height, .depth = depth };
            return @constCast(self);
        }
        /// Queues a 2D image definition via `glTexImage2D`.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: Texture target.
        ///   - level: Mipmap level.
        ///   - internalformat: Sized internal format.
        ///   - width: Width in texels.
        ///   - height: Height in texels.
        ///   - border: Border width (must be 0 in modern GL).
        ///   - format: External pixel format.
        ///   - kind: Data type of pixel data.
        ///   - pixels: Pointer to pixel data or null.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setImage2D(self: *const Editor, target: gl.textures.TextureTarget, level: i32, internalformat: gl.textures.InternalFormat, width: i32, height: i32, border: i32, format: gl.textures.PixelFormat, kind: gl.enums.DataType, pixels: ?*const anyopaque) *const Editor {
            @constCast(self)._pending_image2d = .{ .target = target, .level = level, .internalformat = internalformat, .width = width, .height = height, .border = border, .format = format, .kind = kind, .pixels = pixels };
            return @constCast(self);
        }
        /// Queues a 3D image definition via `glTexImage3D`.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: Texture target.
        ///   - level: Mipmap level.
        ///   - internalformat: Sized internal format.
        ///   - width: Width in texels.
        ///   - height: Height in texels.
        ///   - depth: Depth in texels.
        ///   - border: Border width.
        ///   - format: External pixel format.
        ///   - kind: Data type of pixel data.
        ///   - pixels: Pointer to pixel data or null.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setImage3D(self: *const Editor, target: gl.textures.TextureTarget, level: i32, internalformat: gl.textures.InternalFormat, width: i32, height: i32, depth: i32, border: i32, format: gl.textures.PixelFormat, kind: gl.enums.DataType, pixels: ?*const anyopaque) *const Editor {
            @constCast(self)._pending_image3d = .{ .target = target, .level = level, .internalformat = internalformat, .width = width, .height = height, .depth = depth, .border = border, .format = format, .kind = kind, .pixels = pixels };
            return @constCast(self);
        }
        /// Queues a 2D sub-image update via `glTexSubImage2D`.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: Texture target.
        ///   - level: Mipmap level to update.
        ///   - xoffset: X offset within the texture.
        ///   - yoffset: Y offset within the texture.
        ///   - width: Width of the sub-region.
        ///   - height: Height of the sub-region.
        ///   - format: External pixel format.
        ///   - kind: Data type of pixel data.
        ///   - pixels: Pointer to pixel data or null.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setSubImage2D(self: *const Editor, target: gl.textures.TextureTarget, level: i32, xoffset: i32, yoffset: i32, width: i32, height: i32, format: gl.textures.PixelFormat, kind: gl.enums.DataType, pixels: ?*const anyopaque) *const Editor {
            @constCast(self)._pending_sub2d = .{ .target = target, .level = level, .xoffset = xoffset, .yoffset = yoffset, .width = width, .height = height, .format = format, .kind = kind, .pixels = pixels };
            return @constCast(self);
        }
        /// Queues a 3D sub-image update via `glTexSubImage3D`.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: Texture target.
        ///   - level: Mipmap level to update.
        ///   - xoffset: X offset.
        ///   - yoffset: Y offset.
        ///   - zoffset: Z offset.
        ///   - width: Width of the sub-region.
        ///   - height: Height of the sub-region.
        ///   - depth: Depth of the sub-region.
        ///   - format: External pixel format.
        ///   - kind: Data type of pixel data.
        ///   - pixels: Pointer to pixel data or null.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setSubImage3D(self: *const Editor, target: gl.textures.TextureTarget, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, format: gl.textures.PixelFormat, kind: gl.enums.DataType, pixels: ?*const anyopaque) *const Editor {
            @constCast(self)._pending_sub3d = .{ .target = target, .level = level, .xoffset = xoffset, .yoffset = yoffset, .zoffset = zoffset, .width = width, .height = height, .depth = depth, .format = format, .kind = kind, .pixels = pixels };
            return @constCast(self);
        }
        /// Queues a compressed 2D image via `glCompressedTexImage2D`.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: Texture target.
        ///   - level: Mipmap level.
        ///   - internalformat: Compressed internal format.
        ///   - width: Width in texels.
        ///   - height: Height in texels.
        ///   - border: Border width.
        ///   - image_size: Size of compressed data in bytes.
        ///   - data: Pointer to compressed data or null.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setCompressedImage2D(self: *const Editor, target: gl.textures.TextureTarget, level: i32, internalformat: gl.textures.InternalFormat, width: i32, height: i32, border: i32, image_size: i32, data: ?*const anyopaque) *const Editor {
            @constCast(self)._pending_compressed2d = .{ .target = target, .level = level, .internalformat = internalformat, .width = width, .height = height, .border = border, .image_size = image_size, .data = data };
            return @constCast(self);
        }
        /// Queues a compressed 3D image via `glCompressedTexImage3D`.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: Texture target.
        ///   - level: Mipmap level.
        ///   - internalformat: Compressed internal format.
        ///   - width: Width in texels.
        ///   - height: Height in texels.
        ///   - depth: Depth in texels.
        ///   - border: Border width.
        ///   - image_size: Size of compressed data in bytes.
        ///   - data: Pointer to compressed data or null.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setCompressedImage3D(self: *const Editor, target: gl.textures.TextureTarget, level: i32, internalformat: gl.textures.InternalFormat, width: i32, height: i32, depth: i32, border: i32, image_size: i32, data: ?*const anyopaque) *const Editor {
            @constCast(self)._pending_compressed3d = .{ .target = target, .level = level, .internalformat = internalformat, .width = width, .height = height, .depth = depth, .border = border, .image_size = image_size, .data = data };
            return @constCast(self);
        }
        /// Queues a framebuffer copy to a 2D texture via `glCopyTexImage2D`.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: Texture target.
        ///   - level: Mipmap level.
        ///   - internalformat: Sized internal format for the new image.
        ///   - x: Window X coordinate of the lower-left corner to copy from.
        ///   - y: Window Y coordinate of the lower-left corner to copy from.
        ///   - width: Width of the region to copy.
        ///   - height: Height of the region to copy.
        ///   - border: Border width.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setCopyImage2D(self: *const Editor, target: gl.textures.TextureTarget, level: i32, internalformat: gl.textures.InternalFormat, x: i32, y: i32, width: i32, height: i32, border: i32) *const Editor {
            @constCast(self)._pending_copy2d = .{ .target = target, .level = level, .internalformat = internalformat, .x = x, .y = y, .width = width, .height = height, .border = border };
            return @constCast(self);
        }
        /// Queues a framebuffer copy to a 2D sub-image via `glCopyTexSubImage2D`.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: Texture target.
        ///   - level: Mipmap level.
        ///   - xoffset: X offset within the texture.
        ///   - yoffset: Y offset within the texture.
        ///   - x: Window X coordinate to copy from.
        ///   - y: Window Y coordinate to copy from.
        ///   - width: Width of the region.
        ///   - height: Height of the region.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setCopySubImage2D(self: *const Editor, target: gl.textures.TextureTarget, level: i32, xoffset: i32, yoffset: i32, x: i32, y: i32, width: i32, height: i32) *const Editor {
            @constCast(self)._pending_copy_sub2d = .{ .target = target, .level = level, .xoffset = xoffset, .yoffset = yoffset, .x = x, .y = y, .width = width, .height = height };
            return @constCast(self);
        }
        /// Queues a framebuffer copy to a 3D sub-image via `glCopyTexSubImage3D`.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - target: Texture target.
        ///   - level: Mipmap level.
        ///   - xoffset: X offset within the texture.
        ///   - yoffset: Y offset within the texture.
        ///   - zoffset: Z offset within the texture.
        ///   - x: Window X coordinate to copy from.
        ///   - y: Window Y coordinate to copy from.
        ///   - width: Width of the region.
        ///   - height: Height of the region.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setCopySubImage3D(self: *const Editor, target: gl.textures.TextureTarget, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, x: i32, y: i32, width: i32, height: i32) *const Editor {
            @constCast(self)._pending_copy_sub3d = .{ .target = target, .level = level, .xoffset = xoffset, .yoffset = yoffset, .zoffset = zoffset, .x = x, .y = y, .width = width, .height = height };
            return @constCast(self);
        }
        /// Queues a minification filter change.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - filter: New minification filter.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setMinFilter(self: *const Editor, filter: gl.textures.TextureMinFilter) *const Editor {
            @constCast(self)._pending_min_filter = filter;
            return @constCast(self);
        }
        /// Queues a magnification filter change.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - filter: New magnification filter.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setMagFilter(self: *const Editor, filter: gl.textures.TextureMagFilter) *const Editor {
            @constCast(self)._pending_mag_filter = filter;
            return @constCast(self);
        }
        /// Queues a wrap mode change for S coordinate.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - wrap: New wrap mode for S.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setWrapS(self: *const Editor, wrap: gl.textures.TextureWrap) *const Editor {
            @constCast(self)._pending_wrap_s = wrap;
            return @constCast(self);
        }
        /// Queues a wrap mode change for T coordinate.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - wrap: New wrap mode for T.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setWrapT(self: *const Editor, wrap: gl.textures.TextureWrap) *const Editor {
            @constCast(self)._pending_wrap_t = wrap;
            return @constCast(self);
        }
        /// Queues a wrap mode change for R coordinate.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - wrap: New wrap mode for R.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setWrapR(self: *const Editor, wrap: gl.textures.TextureWrap) *const Editor {
            @constCast(self)._pending_wrap_r = wrap;
            return @constCast(self);
        }
        /// Queues wrap mode changes for S and T coordinates.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - s: Wrap mode for S.
        ///   - t: Wrap mode for T.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setWrap(self: *const Editor, s: gl.textures.TextureWrap, t: gl.textures.TextureWrap) *const Editor {
            @constCast(self)._pending_wrap_s = s;
            @constCast(self)._pending_wrap_t = t;
            return @constCast(self);
        }
        /// Queues wrap mode changes for S, T and R coordinates.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - s: Wrap mode for S.
        ///   - t: Wrap mode for T.
        ///   - r: Wrap mode for R.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setWrapSTR(self: *const Editor, s: gl.textures.TextureWrap, t: gl.textures.TextureWrap, r: gl.textures.TextureWrap) *const Editor {
            @constCast(self)._pending_wrap_s = s;
            @constCast(self)._pending_wrap_t = t;
            @constCast(self)._pending_wrap_r = r;
            return @constCast(self);
        }
        /// Queues a depth comparison mode change.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - mode: New comparison mode.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setCompareMode(self: *const Editor, mode: gl.textures.CompareMode) *const Editor {
            @constCast(self)._pending_compare_mode = mode;
            return @constCast(self);
        }
        /// Queues a depth comparison function change.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - func: New comparison function.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setCompareFunc(self: *const Editor, func: gl.textures.CompareFunc) *const Editor {
            @constCast(self)._pending_compare_func = func;
            return @constCast(self);
        }
        /// Queues a base level change.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - level: New base level.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setBaseLevel(self: *const Editor, level: i32) *const Editor {
            @constCast(self)._pending_base_level = level;
            return @constCast(self);
        }
        /// Queues a maximum level change.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - level: New maximum level.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setMaxLevel(self: *const Editor, level: i32) *const Editor {
            @constCast(self)._pending_max_level = level;
            return @constCast(self);
        }
        /// Queues a minimum LOD change.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - lod: New minimum LOD.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setMinLod(self: *const Editor, lod: f32) *const Editor {
            @constCast(self)._pending_min_lod = lod;
            return @constCast(self);
        }
        /// Queues a maximum LOD change.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - lod: New maximum LOD.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setMaxLod(self: *const Editor, lod: f32) *const Editor {
            @constCast(self)._pending_max_lod = lod;
            return @constCast(self);
        }
        /// Queues a swizzle change for the red channel.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - swizzle: New swizzle value for red.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setSwizzleR(self: *const Editor, swizzle: gl.textures.Swizzle) *const Editor {
            @constCast(self)._pending_swizzle_r = swizzle;
            return @constCast(self);
        }
        /// Queues a swizzle change for the green channel.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - swizzle: New swizzle value for green.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setSwizzleG(self: *const Editor, swizzle: gl.textures.Swizzle) *const Editor {
            @constCast(self)._pending_swizzle_g = swizzle;
            return @constCast(self);
        }
        /// Queues a swizzle change for the blue channel.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - swizzle: New swizzle value for blue.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setSwizzleB(self: *const Editor, swizzle: gl.textures.Swizzle) *const Editor {
            @constCast(self)._pending_swizzle_b = swizzle;
            return @constCast(self);
        }
        /// Queues a swizzle change for the alpha channel.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - swizzle: New swizzle value for alpha.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setSwizzleA(self: *const Editor, swizzle: gl.textures.Swizzle) *const Editor {
            @constCast(self)._pending_swizzle_a = swizzle;
            return @constCast(self);
        }
        /// Queues swizzle changes for all four channels.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - r: Swizzle for red channel.
        ///   - g: Swizzle for green channel.
        ///   - b: Swizzle for blue channel.
        ///   - a: Swizzle for alpha channel.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setSwizzle(self: *const Editor, r: gl.textures.Swizzle, g: gl.textures.Swizzle, b: gl.textures.Swizzle, a: gl.textures.Swizzle) *const Editor {
            @constCast(self)._pending_swizzle_r = r;
            @constCast(self)._pending_swizzle_g = g;
            @constCast(self)._pending_swizzle_b = b;
            @constCast(self)._pending_swizzle_a = a;
            return @constCast(self);
        }
        /// Queues mipmap generation on next `apply`.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - gen: True to generate mipmaps, false to skip.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setGenerateMipmap(self: *const Editor, gen: bool) *const Editor {
            @constCast(self)._pending_generate_mipmap = gen;
            return @constCast(self);
        }
        /// Queues a generic integer texture parameter.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - pname: Parameter name.
        ///   - param: Integer value to set.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setParameterI(self: *const Editor, pname: gl.textures.TextureParameter, param: i32) *const Editor {
            @constCast(self)._pending_param_i = .{ .pname = pname, .param = param };
            return @constCast(self);
        }
        /// Queues a generic float texture parameter.
        /// Parameters:
        ///   - self: Editor instance.
        ///   - pname: Parameter name.
        ///   - param: Floating point value to set.
        /// Returns:
        ///   - Pointer to the editor for chaining.
        pub fn setParameterF(self: *const Editor, pname: gl.textures.TextureParameter, param: f32) *const Editor {
            @constCast(self)._pending_param_f = .{ .pname = pname, .param = param };
            return @constCast(self);
        }

        /// Applies all queued changes to the GL texture object.
        /// Binds the texture, executes any pending storage, image, sub-image, compressed
        /// and copy operations, updates filtering, wrapping, comparison, LOD, swizzle
        /// and generic parameters, generates mipmaps if requested, and resets the editor.
        /// Parameters:
        ///   - self: Editor instance holding pending changes.
        /// Returns:
        ///   - void.
        pub fn apply(self: *const Editor) void {
            const m = @constCast(self)._texture.impl();
            const loaded = gl.loader.loaded();
            const effective_target = @constCast(self)._pending_target orelse m.target;
            if (@constCast(self)._pending_active_unit) |unit| {
                if (loaded) gl.textures.activeTexture(unit);
                m.active_unit = unit;
            }
            if (loaded) gl.textures.bind(effective_target, m.id);
            if (@constCast(self)._pending_target) |t| m.target = t;
            if (@constCast(self)._pending_storage2d) |s| {
                if (loaded) gl.textures.storage2d(s.target, s.levels, s.internalformat, s.width, s.height);
                m.internal_format = s.internalformat;
                m.width = s.width;
                m.height = s.height;
                m.levels = s.levels;
                m.target = s.target;
            }
            if (@constCast(self)._pending_storage3d) |s| {
                if (loaded) gl.textures.storage3d(s.target, s.levels, s.internalformat, s.width, s.height, s.depth);
                m.internal_format = s.internalformat;
                m.width = s.width;
                m.height = s.height;
                m.depth = s.depth;
                m.levels = s.levels;
                m.target = s.target;
            }
            if (@constCast(self)._pending_image2d) |i| {
                if (loaded) gl.textures.image2d(i.target, i.level, i.internalformat, i.width, i.height, i.border, i.format, i.kind, i.pixels);
                m.internal_format = i.internalformat;
                m.width = i.width;
                m.height = i.height;
                m.pixel_format = i.format;
                m.data_type = i.kind;
            }
            if (@constCast(self)._pending_image3d) |i| {
                if (loaded) gl.textures.image3d(i.target, i.level, i.internalformat, i.width, i.height, i.depth, i.border, i.format, i.kind, i.pixels);
                m.internal_format = i.internalformat;
                m.width = i.width;
                m.height = i.height;
                m.depth = i.depth;
                m.pixel_format = i.format;
                m.data_type = i.kind;
            }
            if (@constCast(self)._pending_sub2d) |s| if (loaded) gl.textures.subImage2d(s.target, s.level, s.xoffset, s.yoffset, s.width, s.height, s.format, s.kind, s.pixels);
            if (@constCast(self)._pending_sub3d) |s| if (loaded) gl.textures.subImage3d(s.target, s.level, s.xoffset, s.yoffset, s.zoffset, s.width, s.height, s.depth, s.format, s.kind, s.pixels);
            if (@constCast(self)._pending_compressed2d) |c| {
                if (loaded) gl.textures.compressedImage2d(c.target, c.level, c.internalformat, c.width, c.height, c.border, c.image_size, c.data);
                m.internal_format = c.internalformat;
                m.width = c.width;
                m.height = c.height;
            }
            if (@constCast(self)._pending_compressed3d) |c| {
                if (loaded) gl.textures.compressedImage3d(c.target, c.level, c.internalformat, c.width, c.height, c.depth, c.border, c.image_size, c.data);
                m.internal_format = c.internalformat;
                m.width = c.width;
                m.height = c.height;
                m.depth = c.depth;
            }
            if (@constCast(self)._pending_copy2d) |c| if (loaded) gl.textures.copyImage2d(c.target, c.level, c.internalformat, c.x, c.y, c.width, c.height, c.border);
            if (@constCast(self)._pending_copy_sub2d) |c| if (loaded) gl.textures.copySubImage2d(c.target, c.level, c.xoffset, c.yoffset, c.x, c.y, c.width, c.height);
            if (@constCast(self)._pending_copy_sub3d) |c| if (loaded) gl.textures.copySubImage3d(c.target, c.level, c.xoffset, c.yoffset, c.zoffset, c.x, c.y, c.width, c.height);
            if (@constCast(self)._pending_min_filter) |f| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_min_filter, @intCast(@intFromEnum(f)));
                m.min_filter = f;
            }
            if (@constCast(self)._pending_mag_filter) |f| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_mag_filter, @intCast(@intFromEnum(f)));
                m.mag_filter = f;
            }
            if (@constCast(self)._pending_wrap_s) |w| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_wrap_s, @intCast(@intFromEnum(w)));
                m.wrap_s = w;
            }
            if (@constCast(self)._pending_wrap_t) |w| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_wrap_t, @intCast(@intFromEnum(w)));
                m.wrap_t = w;
            }
            if (@constCast(self)._pending_wrap_r) |w| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_wrap_r, @intCast(@intFromEnum(w)));
                m.wrap_r = w;
            }
            if (@constCast(self)._pending_compare_mode) |v| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_compare_mode, @intCast(@intFromEnum(v)));
                m.compare_mode = v;
            }
            if (@constCast(self)._pending_compare_func) |v| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_compare_func, @intCast(@intFromEnum(v)));
                m.compare_func = v;
            }
            if (@constCast(self)._pending_base_level) |v| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_base_level, v);
                m.base_level = v;
            }
            if (@constCast(self)._pending_max_level) |v| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_max_level, v);
                m.max_level = v;
            }
            if (@constCast(self)._pending_min_lod) |v| {
                if (loaded) gl.textures.parameterF(effective_target, .texture_min_lod, v);
                m.min_lod = v;
            }
            if (@constCast(self)._pending_max_lod) |v| {
                if (loaded) gl.textures.parameterF(effective_target, .texture_max_lod, v);
                m.max_lod = v;
            }
            if (@constCast(self)._pending_swizzle_r) |s| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_swizzle_r, @intCast(@intFromEnum(s)));
                m.swizzle_r = s;
            }
            if (@constCast(self)._pending_swizzle_g) |s| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_swizzle_g, @intCast(@intFromEnum(s)));
                m.swizzle_g = s;
            }
            if (@constCast(self)._pending_swizzle_b) |s| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_swizzle_b, @intCast(@intFromEnum(s)));
                m.swizzle_b = s;
            }
            if (@constCast(self)._pending_swizzle_a) |s| {
                if (loaded) gl.textures.parameterI(effective_target, .texture_swizzle_a, @intCast(@intFromEnum(s)));
                m.swizzle_a = s;
            }
            if (@constCast(self)._pending_param_i) |p| if (loaded) gl.textures.parameterI(effective_target, p.pname, p.param);
            if (@constCast(self)._pending_param_f) |p| if (loaded) gl.textures.parameterF(effective_target, p.pname, p.param);
            if (@constCast(self)._pending_generate_mipmap) {
                if (loaded) gl.textures.generateMipmap(effective_target);
                m.has_mipmap = true;
            }
            @constCast(self).* = Editor.init(@constCast(self)._texture);
        }
    };
};
